/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_apple_ndktest_MainActivity */

#ifndef _Included_com_example_apple_ndktest_MainActivity
#define _Included_com_example_apple_ndktest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_apple_ndktest_MainActivity
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_apple_ndktest_MainActivity_getJniString
        (JNIEnv *, jobject);

/*
 * Class:     com_example_apple_ndktest_MainActivity
 * Method:    getJniInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_apple_ndktest_MainActivity_getJniInt
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif